# Generated by Django 5.2.7 on 2025-10-22 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_alter_area_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('senha', models.CharField(max_length=50, verbose_name='Senha')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('endereço', models.TextField(verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('contato', models.CharField(max_length=15, verbose_name='Telefone')),
                ('endereço', models.TextField(verbose_name='Endereço')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default='Sem categoria', max_length=20, verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(default='Marca padrão', max_length=20, verbose_name='Marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='validade',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Validade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(default='Fornecedor padrão', on_delete=django.db.models.deletion.PROTECT, to='core.fornecedor'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(auto_now_add=True, verbose_name='Data_Pedido')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Desconto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pedido')),
            ],
        ),
    ]
