# Generated by Django 5.2.4 on 2025-12-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cliente_endereço_cliente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='aniversario',
            field=models.DateField(blank=True, null=True, verbose_name='Aniversario'),
        ),
    ]
