# Generated by Django 5.2.7 on 2025-10-22 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_fornecedor_produto_categoria_produto_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor'),
        ),
    ]
