# Generated by Django 5.2.7 on 2025-10-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_produto_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='fornecedor',
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
